---
# Default values for prometheus-es-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

elasticsearch:
  # cluster: <elasticsearch nodes>
  queries: |-
    [DEFAULT]
    QueryIntervalSecs = 15
    QueryTimeoutSecs = 10
    QueryIndices = _all
    QueryOnError = drop
    QueryOnMissing = drop

    [query_all]
    QueryJson = {
        "size": 0,
        "query": {
          "match_all": {}
        }
      }

deployment:
  replicas: 1

pod:
  annotations: {}

image:
  repository: braedon/prometheus-es-exporter
  # tag: <image tag>
  pullPolicy: IfNotPresent

container:
  port: 9206
  portName: prometheus
  extraArgs: []
  resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

service:
  port: 9206
  portName: prometheus
  annotations: {}

serviceMonitor:
  enabled: false
