apiVersion: v1
entries:
  prometheus-es-exporter:
  - apiVersion: v1
    created: "2021-07-09T08:25:15.015994853+08:00"
    description: Run queries on Elasticsearch and export the results as Prometheus
      metrics.
    digest: 442305448f5aeac7bd5513dec4d1f46b60aa6177fe8c2b4c34ed777c81d0fd32
    home: https://github.com/braedon/prometheus-es-exporter
    maintainers:
    - email: braedon.vickers@gmail.com
      name: Braedon Vickers
    name: prometheus-es-exporter
    sources:
    - https://github.com/braedon/prometheus-es-exporter
    urls:
    - https://braedon.github.io/helm/prometheus-es-exporter-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v1
    created: "2020-07-03T22:43:25.904895825+08:00"
    description: Run queries on Elasticsearch and export the results as Prometheus
      metrics.
    digest: 53669c0593a399cd6e4bc64c6da9af4636b58455cd96576ff409efdf1be0ca29
    home: https://github.com/braedon/prometheus-es-exporter
    maintainers:
    - email: braedon.vickers@gmail.com
      name: Braedon Vickers
    name: prometheus-es-exporter
    sources:
    - https://github.com/braedon/prometheus-es-exporter
    urls:
    - https://braedon.github.io/helm/prometheus-es-exporter-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v1
    created: "2020-07-03T22:43:25.90442122+08:00"
    description: Run queries on Elasticsearch and export the results as Prometheus
      metrics.
    digest: da089b73d8b67095d54f838e59c3148c6c58af0890265eebcf8f14dd90b0c605
    home: https://github.com/braedon/prometheus-es-exporter
    maintainers:
    - email: braedon.vickers@gmail.com
      name: Braedon Vickers
    name: prometheus-es-exporter
    sources:
    - https://github.com/braedon/prometheus-es-exporter
    urls:
    - https://braedon.github.io/helm/prometheus-es-exporter-0.1.0.tgz
    version: 0.1.0
  prometheus-mysql-exporter:
  - apiVersion: v1
    created: "2020-09-07T14:19:28.59946306+08:00"
    description: Run queries on Mysql and export the results as Prometheus metrics.
    digest: 83223aa3868be8e874e9071989cb11c93292aff23032c7d80cc2cc292e336441
    home: https://github.com/braedon/prometheus-mysql-exporter
    maintainers:
    - email: braedon.vickers@gmail.com
      name: Braedon Vickers
    name: prometheus-mysql-exporter
    sources:
    - https://github.com/braedon/prometheus-mysql-exporter
    urls:
    - https://braedon.github.io/helm/prometheus-mysql-exporter-0.1.0.tgz
    version: 0.1.0
generated: "2021-07-09T08:25:15.014886345+08:00"
