apiVersion: v1
entries:
  prometheus-es-exporter:
  - apiVersion: v1
    created: "2020-07-03T18:47:39.560001084+08:00"
    description: Run queries on Elasticsearch and export the results as Prometheus
      metrics.
    digest: da089b73d8b67095d54f838e59c3148c6c58af0890265eebcf8f14dd90b0c605
    home: https://github.com/braedon/prometheus-es-exporter
    maintainers:
    - email: braedon.vickers@gmail.com
      name: Braedon Vickers
    name: prometheus-es-exporter
    sources:
    - https://github.com/braedon/prometheus-es-exporter
    urls:
    - https://braedon.github.io/helm/prometheus-es-exporter-0.1.0.tgz
    version: 0.1.0
generated: "2020-07-03T18:47:39.559424144+08:00"
